// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmryoefyouvkpzoeoaow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptcnlvZWZ5b3V2a3B6b2VvYW93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMjM5MzgsImV4cCI6MjA2Nzc5OTkzOH0.F8PTJKABDmuH4zlmMwdVr3aOpzIcaM4q7UxNiZ1MrSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});